### ISSUE TITLE
BungeeCord Funktioniert nicht

### ISSUE THREAD

**Issue by Fuchso** [VironLab/MinecraftDiscordSync#1]
Bei Bungeecord updaten die Spieler zahlen bei Discord nicht. auch die Max Player zahl ist nicht korrekt sondern ist auch 1.

**Comment by depascaldc** [comment]
Da ist ein Timer eingerichtet der alle 3 minuten die zahl updaten sollte ( wenn mit dem update der name des channels anders ist ) damit discords API nicht zu dolle beansprucht wird ( denn sich widerholende aktionen alle x sekunden da hat discord was gegen deswegen eine fixe rate... ) und MAX player anzahl schau ich mir an. Danke für den Report :)

**Comment by Fuchso** [comment]
Nach 10Minuten Passiert da nichts deine angaben sind nicht korrekt oder fehlerhaft!

**Comment by Fuchso** [comment]
Außer dem wird nicht nur der Chat sogar auch die commands angezeigt.!

**Comment by depascaldc** [comment]
Kümmere mich später darum ich lass dich hier wissen sobald das behoben ist und lad das neue plugin dann hoch im release :) Oder du kannst auch unserem discordserver beitreten dort siehst du das sobald der commit eingeht im kanal #gitfeed

**Comment by Fuchso** [comment]
Danke 👍

**Comment by depascaldc** [comment]
So theoretisch sollte das jetzt gehen! :) Tu mir pls nochmal den gefallen und check deine config ob du
 
```yml
guild:
  id: '12345678910111213'
# und
onlinecounter:
  enabled: true
```

angegeben hast. Desweiteren ob der kanal ein voice kanal ist den du angegeben hast :)

Und sollte noch etwas sein meld dich am besten auf den [DiscordServer](https://discord.gg/wvcX92VyEH) von uns.

Und vielen dank nochmal fürs reporten :P
